export const REASON_CODES = {
  READ_ONLY: "READ_ONLY",
  LOW_RISK: "LOW_RISK",
  WITHIN_AUTO_LIMIT: "WITHIN_AUTO_LIMIT",
  AUTO_LIMIT_EXCEEDED: "AUTO_LIMIT_EXCEEDED",
  HARD_SPEND_LIMIT: "HARD_SPEND_LIMIT",
  SESSION_SPEND_LIMIT: "SESSION_SPEND_LIMIT",
  RECURRING_CHARGE: "RECURRING_CHARGE",
  NON_REFUNDABLE: "NON_REFUNDABLE",
  DATA_FIELD_ALLOWED: "DATA_FIELD_ALLOWED",
  DATA_FIELD_REQUIRES_APPROVAL: "DATA_FIELD_REQUIRES_APPROVAL",
  DATA_FIELD_BLOCKED: "DATA_FIELD_BLOCKED",
  DESTRUCTIVE_ACTION: "DESTRUCTIVE_ACTION",
  USER_DENIED: "USER_DENIED",
  EXECUTION_CANCELLED: "EXECUTION_CANCELLED",
  ACTION_CHANGED: "ACTION_CHANGED",
  INVALID_STATE: "INVALID_STATE"
} as const;

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];
